#!/usr/bin/env python3

from urllib.request import Request, urlopen

import importlib
import os
import sys

puzzle_number = sys.argv[1].zfill(2)
bare_puzzle_number = puzzle_number.lstrip('0')
puzzle_dir = f'day-{puzzle_number}'

sys.path.append(f'./{puzzle_dir}/')

if len(sys.argv) > 2 and sys.argv[2] == '--test':
    print(f'Running tests on day {bare_puzzle_number}')
    importlib.import_module(f'{puzzle_dir}.test')
    sys.exit(0)

day = importlib.import_module(f'{puzzle_dir}.run')

token = os.getenv('ADVENTOFCODE_TOKEN')

url = f'https://adventofcode.com/2021/day/{bare_puzzle_number}/input'
req = Request(url)
req.add_header('Cookie', f'session={token}')
data = urlopen(req)
day_input = day.parse_input(data.read().decode('utf-8'))

print(f'Fetched data from {url}')

print(day.part1(day_input))
print(day.part2(day_input))
